networks:
  home_pi:

services:

  apache:
    build: 
      context: .
      dockerfile: docker/apache/Dockerfile
      args:
        # Docker image version
        APACHE_VERSION: "2.4.59" # https://hub.docker.com/_/httpd
        # Build arguments
        ADMIN_EMAIL_ADDRESS: "${ADMIN_EMAIL_ADDRESS?[httpd] Admin email address missing}"
    container_name: apache
    hostname: apache
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"
    environment:
      # Base config
      PGID: "${PGID:?Group ID missing}"
      PUID: "${PUID:?User ID missing}"
      TZ: "${TIMEZONE:?Timezone not set}"
    networks:
      - home_pi
    ports:
      - "80:80"
    restart: unless-stopped

  uptime_kuma:
    image: louislam/uptime-kuma:1.23.12-alpine
    container_name: uptime_kuma
    hostname: uptime-kuma
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "512M"
    environment:
      # Base config
      PGID: "${PGID:?Group ID missing}"
      PUID: "${PUID:?User ID missing}"
      TZ: "${TIMEZONE:?Timezone not set}"
    networks:
      - home_pi
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      # Persistent volumes
      - ./storage/uptime_kuma/:/app/data
