services:
  radarr:
    image: linuxserver/radarr:4.0.5
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - ~/git/home_theatre/storage/radarr:/config
      - /e/Downloads:/downloads
      - /b/Movies:/movies
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland

  sonarr:
    image: linuxserver/sonarr:3.0.7
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ~/git/home_theatre/storage/sonarr:/config
      - /e/Downloads:/downloads
      - /a/TV:/tv
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland

  jackett:
    image: linuxserver/jackett:0.20.790
    container_name: jackett
    hostname: jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    volumes:
      - ~/git/home_theatre/storage/jackett:/config
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland
