include:
  - ./compose/apprise.yml
  - ./compose/authelia.yml
  - ./compose/autokuma-ser.yml
  - ./compose/dash-ser.yml
  - ./compose/dozzle.yml
  - ./compose/homarr.yml
  - ./compose/lldap.yml
  - ./compose/netalert.yml
  - ./compose/speedtest.yml
  - ./compose/traefik.yml
  - ./compose/uptime-kuma.yml
  - ./compose/watchstate.yml
