include:
  - ./compose/audiobookshelf.yml
  - ./compose/autokuma.yml
  - ./compose/bazarr.yml
  - ./compose/dailytxt.yml
  - ./compose/doplarr.yml
  - ./compose/emby.yml
  - ./compose/filebrowser.yml
  - ./compose/homebox.yml
  - ./compose/jellystat.yml
  - ./compose/linkwarden.yml
  - ./compose/navidrome.yml
  - ./compose/prowlarr.yml
  - ./compose/qbittorrent.yml
  - ./compose/romm.yml
  - ./compose/servarr.yml
  - ./compose/sonarqube.yml
  - ./compose/tandoor.yml
  - ./compose/traefik-kop.yml
