networks:
  home_pi:

services:

  apache:
    build: 
      context: .
      dockerfile: docker/apache/Dockerfile
      args:
        # Docker image version
        APACHE_VERSION: "2.4.58" # https://hub.docker.com/_/httpd
    container_name: apache
    hostname: apache
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home_pi
    ports:
      - "80:80"
    restart: always

  uptime_kuma:
    image: louislam/uptime-kuma:1.23.11-alpine
    container_name: uptime_kuma
    hostname: uptime-kuma
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home_pi
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      # Persistent volumes
      - ./storage/uptime_kuma/:/app/data
