services:
  heimdall:
    image: linuxserver/heimdall:2.4.10
    container_name: heimdall
    hostname: heimdall
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland
    volumes:
      - /e/home_theatre/storage/heimdall:/config
    ports:
      - "80:80"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:4.0.5
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - /e/home_theatre/storage/radarr:/config
      - /e/Downloads:/downloads
      - /b/Movies:/movies
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland

  sonarr:
    image: linuxserver/sonarr:3.0.7
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - /e/home_theatre/storage/sonarr:/config
      - /e/Downloads:/downloads
      - /a/TV:/tv
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland

  readarr:
    image: linuxserver/readarr:0.1.0-develop
    container_name: readarr
    hostname: readarr
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland
    volumes:
      - /e/home_theatre/storage/readarr:/config
      - /b/Books:/books
      - /e/Downloads:/downloads
    ports:
      - "8787:8787"
    restart: unless-stopped

  calibre:
    image: linuxserver/calibre:5.40.0
    container_name: calibre
    hostname: calibre
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland
      - PASSWORD=shroot
      - CLI_ARGS="–auth-mode=basic"
    volumes:
      - /e/home_theatre/storage/calibre:/config
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:1.0.3
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland
    volumes:
      - /e/home_theatre/storage/bazarr:/config
      - /b/Movies:/movies
      - /a/TV:/tv
    ports:
      - "6767:6767"
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:0.20.790
    container_name: jackett
    hostname: jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    volumes:
      - /e/home_theatre/storage/jackett:/config
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland

  transmission:
    image: linuxserver/transmission:version-3.00-r5
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland
      - USER=root
      - PASS=shroot
    volumes:
      - /e/home_theatre/storage/transmission:/config
      - /e/Downloads:/downloads
      - /e/TorrentFiles:/watch
    ports:
      - "9091:9091"
      - "5555:51413"
      - "5555:51413/udp"
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:v2.2.2
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Pacific/Auckland
    ports:
      - "8191:8191"
    restart: unless-stopped

  emby:
    image: linuxserver/emby:4.6.7
    container_name: emby
    hostname: emby
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland
    volumes:
      - /e/home_theatre/storage/emby:/config
      - /b/Movies:/data/movies
      - /a/TV:/data/shows
    ports:
      - "8096:8096"
    restart: unless-stopped

  plex:
    image: linuxserver/plex:1.25.9
    container_name: plex
    hostname: plex
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Pacific/Auckland
    volumes:
      - /e/home_theatre/storage/plex:/config
      - /b/Movies:/movies
      - /a/TV:/tv
    ports:
      - "32400:32400"
    restart: unless-stopped
