networks:
  home:

services:

  # Homepage
  homarr:
    image: ghcr.io/ajnart/homarr:0.14.3 # https://github.com/ajnart/homarr/pkgs/container/homarr
    container_name: homarr
    hostname: homarr
    depends_on:
      - qbittorrent
      - radarr
      - sonarr
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "4100:7575"
    restart: unless-stopped
    volumes:
      # Docker socket mount from host system
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
      # Persistent volumes
      - ./storage/homarr/configs:/app/data/configs
      - ./storage/homarr/data:/data
      - ./storage/homarr/icons:/app/public/icons

  # Movie searcher
  radarr:
    image: linuxserver/radarr:version-5.2.6.8376
    container_name: radarr
    hostname: radarr
    depends_on:
      - qbittorrent
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "4000:3000"
    restart: unless-stopped
    volumes:
      # Volume mounts from host system
      - "${DOWNLOADS_DIRECTORY}:/downloads"
      - "${MOVIE_DIRECTORY}:/movies"
      # Persistent volumes
      - ./storage/radarr/:/config

  # TV show searcher
  sonarr:
    image: linuxserver/sonarr:develop-version-4.0.0.747
    container_name: sonarr
    hostname: sonarr
    depends_on:
      - qbittorrent
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2048M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "4001:3001"
    restart: unless-stopped
    volumes:
      # Volume mounts from host system
      - "${DOWNLOADS_DIRECTORY}:/downloads"
      - "${TV1_DIRECTORY}:/tv1"
      - "${TV2_DIRECTORY}:/tv2"
      - "${TV_TRASH_DIRECTORY}:/trash"
      - "${TV_KIDS_DIRECTORY}:/kids"
      # Persistent volumes
      - ./storage/sonarr/:/config

  # Quality profile manager for radarr/sonarr
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:6.0.2 # https://github.com/recyclarr/recyclarr/pkgs/container/recyclarr
    container_name: recyclarr
    hostname: recyclarr
    depends_on:
      - radarr
      - sonarr
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
      CRON_SCHEDULE: "@daily"
      # Sonarr Config
      SONARR_URL: "http://sonarr:3001"
      SONARR_API_KEY: "${SONARR_API_KEY}"
      # Radarr Config
      RADARR_URL: "http://radarr:3000"
      RADARR_API_KEY: "${RADARR_API_KEY}"
    networks:
      - home
    restart: unless-stopped
    volumes:
      - ./storage/recyclarr:/config
      - ./docker/recyclarr/config/recyclarr.yml:/config/recyclarr.yml

  # Music searcher
  lidarr:
    image: linuxserver/lidarr:version-2.0.7.3849
    container_name: lidarr
    hostname: lidarr
    depends_on:
      - qbittorrent
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "4002:3002"
    restart: unless-stopped
    volumes:
      # Volume mounts from host system
      - "${DOWNLOADS_DIRECTORY}:/downloads"
      - "${MUSIC_DIRECTORY}:/music"
      # Persistent volumes
      - ./storage/lidarr/:/config

  # Music Player
  navidrome:
    image: deluan/navidrome:0.50.2
    container_name: navidrome
    hostname: navidrome
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    environment:
      ND_SCANSCHEDULE: "@every 24h"
      ND_LOGLEVEL: "info"
      ND_COVERARTPRIORITY: "album.*, embedded, external"
      ND_ARTISTARTPRIORITY: "artist.*, external"
      # External integrations
      ND_LASTFM_APIKEY: "${LASTFM_API_KEY}"
      ND_LASTFM_SECRET: "${LASTFM_SECRET}"
      ND_SPOTIFY_ID: "${SPOTIFY_CLIENT_ID}"
      ND_SPOTIFY_SECRET: "${SPOTIFY_CLIENT_SECRET}"
    networks:
      - home
    ports:
      - "4003:4533"
    restart: unless-stopped
    volumes:
      # Volume mounts from host system
      - "${MUSIC_DIRECTORY}:/music:ro"
      # Persistent volumes
      - ./storage/navidrome/:/data

  # Book searcher
  readarr:
    image: linuxserver/readarr:develop-version-0.3.14.2348
    container_name: readarr
    hostname: readarr
    depends_on:
      - qbittorrent
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "512M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "4004:3004"
    restart: unless-stopped
    volumes:
      # Volume mounts from host system
      - "${BOOKS_DIRECTORY}:/books"
      - "${DOWNLOADS_DIRECTORY}:/downloads"
      # Persistent volumes
      - ./storage/readarr/:/config

  # eBook management
  calibre:
    image: linuxserver/calibre:7.2.0
    container_name: calibre
    hostname: calibre
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"
    environment:
      GUAC_USER: "abc" # Hardcoded value
      GUAC_PASS: "${CALIBRE_PASSWORD}"
      USERNAME: "abc" # Hardcoded value
      PASSWORD: "${CALIBRE_PASSWORD}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "4005:8080"
      - "4006:8081"
    restart: unless-stopped
    volumes:
      # Volume mounts from host system
      - "${BOOK_COVERS_DIRECTORY}:/covers"
      # Persistent volumes
      - ./storage/calibre/:/config
      - "calibre_library_1:/${BOOK_LIBRARY_1}"
      - "calibre_library_2:/${BOOK_LIBRARY_2}"

  # Default credentials: admin/admin123
  calibre-web-1:
    image: linuxserver/calibre-web:0.6.21
    container_name: calibre-web-1
    hostname: calibre-web-1
    depends_on:
      - calibre
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "4007:8083"
    restart: unless-stopped
    volumes:
      # Persistent volumes
      - "calibre_library_1:/${BOOK_LIBRARY_1}"
      - ./storage/calibre-web-1/:/config

  # Default credentials: admin/admin123
  calibre-web-2:
    image: linuxserver/calibre-web:0.6.21
    container_name: calibre-web-2
    hostname: calibre-web-2
    depends_on:
      - calibre
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "4008:8083"
    restart: unless-stopped
    volumes:
      # Persistent volumes
      - "calibre_library_2:/${BOOK_LIBRARY_2}"
      - ./storage/calibre-web-2/:/config

  # Downloaded archive extracter
  unpackerr:
    image: golift/unpackerr:0.12.0
    container_name: unpackerr
    hostname: unpackerr
    depends_on:
      - lidarr
      - radarr
      - sonarr
      # - readarr
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "512M"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
      # Sonarr Config
      UN_SONARR_0_URL: "http://sonarr:3001"
      UN_SONARR_0_API_KEY: "${SONARR_API_KEY}"
      UN_SONARR_0_PATHS_0: "/downloads/complete/sonarr"
      UN_SONARR_0_PROTOCOLS: "torrent,usenet"
      # Radarr Config
      UN_RADARR_0_URL: "http://radarr:3000"
      UN_RADARR_0_API_KEY: "${RADARR_API_KEY}"
      UN_RADARR_0_PATHS_0: "/downloads/complete/radarr"
      UN_RADARR_0_PROTOCOLS: "torrent,usenet"
      # Lidarr Config
      UN_LIDARR_0_URL: "http://lidarr:3002"
      UN_LIDARR_0_API_KEY: "${LIDARR_API_KEY}"
      UN_LIDARR_0_PATHS_0: "/downloads/complete/lidarr"
      UN_LIDARR_0_PROTOCOLS: "torrent,usenet"
      # Readarr Config
      UN_READARR_0_URL: "http://readarr:3004"
      UN_READARR_0_API_KEY: "${READARR_API_KEY}"
      UN_READARR_0_PATHS_0: "/downloads/complete/readarr"
      UN_READARR_0_PROTOCOLS: "torrent,usenet"
    networks:
      - home
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "${PUID}:${PGID}"
    volumes:
      - "${DOWNLOADS_DIRECTORY}:/downloads"
      - ./storage/unpackerr/:/config

  # Subtitle downloader
  bazarr:
    build:
      context: .
      dockerfile: docker/bazarr/Dockerfile
      args:
        # Docker image versions
        BAZARR_VERSION: "1.3.1" # https://hub.docker.com/r/linuxserver/bazarr/tags
    container_name: bazarr
    hostname: bazarr
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "512M"
    depends_on:
      - radarr
      - sonarr
      - whisper
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "4009:3009"
    restart: unless-stopped
    volumes:
      # Volume mounts from host system
      - "${MOVIE_DIRECTORY}:/movies"
      - "${TV1_DIRECTORY}:/tv1"
      - "${TV2_DIRECTORY}:/tv2"
      - "${TV_TRASH_DIRECTORY}:/trash"
      - "${TV_KIDS_DIRECTORY}:/kids"
      # Persistent volumes
      - ./storage/bazarr/:/config

  # Automated Speech Recognition tool for subtitles
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:v1.2.4
    container_name: whisper
    hostname: whisper
    environment:
      ASR_MODEL: "small.en"
      ASR_ENGINE: "faster_whisper"
    networks:
      - home
    ports:
      - "4012:9000"
    restart: unless-stopped

  # Video Game ROM Manager
  romm:
    image: zurdi15/romm:2.3.1
    container_name: romm
    hostname: romm
    environment:
      # Database config
      ROMM_DB_DRIVER: "sqlite"
      # External systems config
      IGDB_CLIENT_ID: "${TWITCH_CLIENT_ID}"
      IGDB_CLIENT_SECRET: "${TWITCH_CLIENT_SECRET}"
      STEAMGRIDDB_API_KEY: "${STEAMGRIDDB_API_KEY}"
      # Authentication config
      ROMM_AUTH_ENABLED: "true"
      ROMM_AUTH_SECRET_KEY: "${ROMM_SECRET_KEY}"
      ROMM_AUTH_USERNAME: "${ADMIN_USERNAME}"
      ROMM_AUTH_PASSWORD: "${ROMM_ADMIN_PASSWORD}"
      ENABLE_EXPERIMENTAL_REDIS: "true"
      REDIS_HOST: "romm-users-cache"
      REDIS_PORT: "6379"
    networks:
      - home
    ports:
      - "4013:8080"
    restart: "unless-stopped"
    volumes:
      # Volume mounts from host system
      - "${ROMS_DIRECTORY}:/romm/library/roms:ro"
      - "./docker/romm/config/config.yml:/romm/config.yml"
      # Persistent volumes
      - ./storage/romm/database/:/romm/database
      - ./storage/romm/resources/:/romm/resources
      - ./storage/romm/logs:/romm/logs

  # Redis cache for RomM users
  romm_users_cache:
    image: redis:7.2.3-alpine
    container_name: romm_users_cache
    hostname: romm-users-cache
    networks:
      - home
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      # Volume mounts from host system
      - "./docker/romm/config/redis_sysctl.conf:/etc/sysctl.conf"
      # Persistent volumes
      - ./storage/redis/:/data

  # Indexer (Torrents + Usenet)
  prowlarr:
    image: linuxserver/prowlarr:version-1.11.4.4173
    container_name: prowlarr
    hostname: prowlarr
    depends_on:
      - flaresolverr
      - lidarr
      - radarr
      - readarr
      - sonarr
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M" # High memory resourcing to allow stats page to load
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "9696:9696"
    restart: unless-stopped
    volumes:
      # Persistent volumes
      - ./storage/prowlarr/:/config

  # Torrent downloader
  qbittorrent:
    build:
      context: .
      dockerfile: docker/qbittorrent/Dockerfile
      args:
        # Docker image versions
        QBITTORRENT_VERSION: "4.6.2" # https://hub.docker.com/r/linuxserver/qbittorrent/tags
        # Build arguments
        VUETORRENT_VERSION: "2.4.0" # https://github.com/WDaan/VueTorrent/releases/
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TIMEZONE}"
      WEBUI_PORT: "9000"
    networks:
      - home
    ports:
      - "9000-9002:9000-9002"
      # Additional ports to help connect to trackers/improve traffic
      - "6881-6969:6881-6969"
    restart: unless-stopped
    volumes:
      # Volume mounts from host system
      - "${DOWNLOADS_DIRECTORY}:/downloads"
      # Persistent volumes
      - ./storage/qbittorrent/:/config

  # Discord bot for requests
  doplarr:
    image: linuxserver/doplarr:3.6.2
    container_name: doplarr
    hostname: doplarr
    depends_on:
      - radarr
      - sonarr
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    environment:
      # Integration configuration
      RADARR__URL: "http://radarr:3000"
      SONARR__URL: "http://sonarr:3001"
      RADARR__API: "${RADARR_API_KEY}"
      SONARR__API: "${SONARR_API_KEY}"
      # Discord configuration
      DISCORD__TOKEN: "${DISCORD_BOT_TOKEN}"
      DISCORD__MAX_RESULTS: 5
    networks:
      - home
    restart: unless-stopped

  # Cloudflare rate-limiter solver
  flaresolverr:
    image: ghcr.io/aeonlucid/flaresolverr:v3.3.2-hotfix # https://github.com/aeonlucid/FlareSolverr/pkgs/container/flaresolverr
    container_name: flaresolverr
    hostname: flaresolverr
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    environment:
      LOG_LEVEL: info
      TZ: "${TIMEZONE}"
    networks:
      - home
    ports:
      - "8191:8191"
    restart: unless-stopped

  # Recipe manager (Tandoor, but container cannot be renamed)
  web_recipes:
    image: vabene1111/recipes:1.5.10
    container_name: web_recipes
    hostname: web_recipes
    depends_on:
      - postgres
    environment:
      TZ: "${TIMEZONE}"
      SECRET_KEY: "${TANDOOR_SECRET_KEY}"
      DB_ENGINE: "django.db.backends.postgresql"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      DEBUG: "0"
      SQL_DEBUG: "0"
    networks:
      - home
    restart: unless-stopped
    volumes:
      - ./storage/tandoor/nginx/conf.d/:/opt/recipes/nginx/conf.d
      - ./storage/tandoor/mediafiles/:/opt/recipes/mediafiles
      - ./storage/tandoor/staticfiles/:/opt/recipes/staticfiles

  # Recipe manager reverse-proxy/UI
  tandoor_ui:
    image: nginx:1.25.3-alpine
    container_name: tandoor_ui
    hostname: tandoor-ui
    depends_on:
      - web_recipes
    environment:
      TIMEZONE: "${TIMEZONE}"
      SECRET_KEY: "${TANDOOR_SECRET_KEY}"
    networks:
      - home
    ports:
      - "4010:80"
    restart: unless-stopped
    volumes:
      - ./storage/tandoor/nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./storage/tandoor/mediafiles/:/media:ro
      - ./storage/tandoor/staticfiles/:/static:ro

  # Inventory management
  homebox:
    image: ghcr.io/hay-kot/homebox:v0.10.3 # https://github.com/hay-kot/homebox/pkgs/container/homebox
    container_name: homebox
    hostname: homebox
    environment:
      HBOX_LOG_LEVEL: "info"
      HBOX_LOG_FORMAT: "text"
      HBOX_WEB_MAX_UPLOAD_SIZE: "10"
      HBOX_OPTIONS_ALLOW_REGISTRATION: "false"
    networks:
      - home
    ports:
      - "4011:7745"
    restart: unless-stopped
    volumes:
      - ./storage/homebox/:/data/

  # Daily journal
  dailytxt:
    image: phitux/dailytxt:1.0.13
    container_name: dailytxt
    hostname: dailytxt
    environment:
      USER_UID: "${PUID}"
      USER_GID: "${PGID}"
      TZ: "${TIMEZONE}"
      PORT: "8765"
      SECRET_KEY: "${DAILYTXT_SECRET_KEY}"
      ALLOW_REGISTRATION: "false"
      DATA_INDENT: "2"
      JWT_EXP_DAYS: "60"
      ENABLE_UPDATE_CHECK: "false"
    networks:
      - home
    ports:
      - "4015:8765"
    restart: unless-stopped
    volumes:
      - ./storage/dailytxt/:/app/data/

  # Log aggregator
  dozzle:
    build:
      context: .
      dockerfile: docker/dozzle/Dockerfile
      args:
        # Docker image versions
        DEBIAN_VERSION: "12.4" # https://hub.docker.com/_/debian/tags
        DOZZLE_VERSION: "v6.0.0" # https://hub.docker.com/r/amir20/dozzle/tags
        # Build arguments
        ADMIN_EMAIL_ADDRESS: "${ADMIN_EMAIL_ADDRESS}"
        ADMIN_USERNAME: "${ADMIN_USERNAME}"
        ADMIN_PASSWORD: "${DOZZLE_PASSWORD}"
    container_name: dozzle
    hostname: dozzle
    environment:
      DOZZLE_AUTH_PROVIDER: "simple"
    networks:
      - home
    ports:
      - "4014:8080"
    restart: unless-stopped
    volumes:
      # Docker socket mount from host system
      - "${DOCKER_SOCKET}:/var/run/docker.sock"

  # Database
  postgres:
    image: postgres:15.5-alpine
    container_name: postgres
    hostname: postgres
    environment:
      TIMEZONE: "${TIMEZONE}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    networks:
      - home
    restart: unless-stopped
    volumes:
      - ./storage/postgres/:/var/lib/postgresql/data

volumes:
  # Calibre libraries for multiple users
  calibre_library_1: { }
  calibre_library_2: { }
