exclude:
  platforms: [ ]
  roms:
    multi_file:
      names:
        - ".Trash*"
      parts:
        extensions: [ ]
        names: [ ]
    single_file:
      extensions:
        - jpg
        - jpeg
        - png
        - webp
        - xml
      names: [ ]

filesystem:
  firmware_folder: bios
  roms_folder: roms

system:
  platforms:
    3DS: 3ds
    DS: nds
    Flash: browser
    GameBoy: gb
    GameBoyAdvance: gba
    GameBoyColor: gbc
    GameCube: ngc
    N64: n64
    PS: psx
    PS2: ps2
    PS3: ps3
    PSP: psp
    PSVita: psvita
    SegaGenesis: genesis
    Switch: switch
    Wii: wii
    Windows: win
    XBox: xbox
    XBox360: xbox360
  versions: { }

gamelist:
  export:
    local_video: true

# Metadata priority during scans
scan:
  export:
    gamelist_xml: true
  priority:
    metadata:
      - "gamelist"   # ES-DE gamelist.xml
      - "igdb"       # IGDB
      - "ra"         # RetroAchievements
      - "hasheous"   # Hasheous
      - "flashpoint" # Flashpoint Project
      - "hltb"       # HowLongToBeat
      - "ss"         # Screenscraper
    artwork:
      - "gamelist"   # ES-DE gamelist.xml
      - "igdb"       # IGDB
      - "ra"         # RetroAchievements
      - "hasheous"   # Hasheous
      - "flashpoint" # Flashpoint Project
      - "hltb"       # HowLongToBeat
      - "ss"         # Screenscraper
    media:
      - "box2d"
      - "screenshot"
      - "manual"
      - "title_screen"
      - "marquee"
    region: # Cover art and game title (only used by Screenscraper)
      - "eu"
      - "wor"
      - "us"
      - "ss"
      - "jp"
    language: # Cover art and game title (only used by Screenscraper)
      - "en"
