---
check_interval: 5s

monitors:
  - name: Emby
    command: [ "curl", "-s", "-o", "/dev/null", "--max-time", "10", "https://emby.zodac.me" ]
    alert_down: [ discord_down ]
    alert_up: [ discord_up ]
    check_interval: 60s # Must be at least equal to the global 'check_interval'
    alert_after: 5
    alert_every: 0 # -1 for exponential backoff, 0 to disable repeating

alerts:
  discord_up:
    command: >
      curl -s -X POST
      -H "Accept: application/json"
      -H "Content-Type: application/json"
      --data "{\"content\": \"Emby server ONLINE: $(date)\"}"
      "${DISCORD_MEDIA_SERVER_ONLINE_WEBHOOK_URL}"
  discord_down:
    command: >
      curl -s -X POST
      -H "Accept: application/json"
      -H "Content-Type: application/json"
      --data "{\"content\": \"Emby server OFFLINE: $(date)\"}"
      "${DISCORD_MEDIA_SERVER_OFFLINE_WEBHOOK_URL}"
