ARG QBITTORRENT_VERSION
FROM linuxserver/qbittorrent:${QBITTORRENT_VERSION}
COPY ./docker/qbittorrent/config/qbittorrent.qbtheme /tmp/qbittorrent.qbtheme
COPY ./docker/qbittorrent/config/qBittorrent.conf /config/qBittorrent/qBittorrent.conf
