http:
  middlewares:
    authelia-forward-auth:
      chain:
        middlewares:
          - authelia@file
          - authelia-error-redirect@file
          - rate-limit@file
          - secure-headers@file
