# Configuration file for services that are not handled by the main docker service, such as file-provider
# sourced services, or redis-provider services that are on external docker hosts.
#
# Since Traefik can't dynamically remove routes as these services go down, we need to explicitly handle
# errors when a service is down by checking for a 400-599 HTTP status code, then redirecting to an
# appropriate web page.
http:
  middlewares:
    redirect-on-error:
      plugin:
        traefik-plugin-redirect-on-status:
          redirectUri: "{{ env "STATUS_URL" | trimAll "\"" }}"
          status:
            - "400-599"
