http:
  routers:
    emby-router:
      rule: "Host(`emby.{{ env "DOMAIN_NAME" | trimAll "\"" }}`)"
      service: emby-service
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - no-forward-auth@file
        - redirect-on-error@file

  services:
    emby-service:
      loadBalancer:
        servers:
          - url: "{{ env "EMBY_URL" | trimAll "\"" }}"
