networks:
  apprise:
    name: apprise
    driver: bridge

services:

  # Centralised notification manager
  apprise:
    image: caronc/apprise:1.3.1  # https://hub.docker.com/r/caronc/apprise/tags | https://github.com/caronc/apprise-api/releases
    container_name: apprise
    hostname: apprise
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    cap_drop:
      - ALL
    environment:
      # Application configuration
      APPRISE_ADMIN: "y"
      APPRISE_STATEFUL_MODE: "simple"
      APPRISE_WORKER_COUNT: "1"
      # Logging configuration
      DEBUG: "no"
      LOG_LEVEL: "INFO"
      # Secrets configuration
      SECRET_KEY: "${APPRISE_SECRET_KEY:-[apprise] Secret key missing}"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "curl", "--silent", "--fail", "http://127.0.0.1:8000/status" ] # wget not installed
      timeout: 5s
    labels:
      # Reverse proxy config
      traefik.enable: "true"
      traefik.docker.network: "apprise"
      traefik.http.routers.apprise.rule: "Host(`apprise.${DOMAIN_NAME}`)"
      traefik.http.routers.apprise.entrypoints: "websecure"
      traefik.http.routers.apprise.tls: "true"
      traefik.http.routers.apprise.middlewares: "authelia-forward-auth@file"
      # Monitor config
      kuma.apprise.http.name: "Apprise (Centralised Notifications)"
      kuma.apprise.http.url: "${APPRISE_MONITOR_URL:?[apprise] Monitor URL missing}"
    networks:
      - apprise
    ports:
      - "5007:8000"
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"
    volumes:
      # Persistent volumes
      - ../storage/apprise/attach:/attach
      - ../storage/apprise/config:/config
      - ../storage/apprise/plugin:/plugin
