networks:
  autokuma:
    name: autokuma
    driver: bridge

services:

  # Automatic Uptime-Kuma monitor generator
  autokuma:
    image: ghcr.io/bigboot/autokuma:2.0.0  # https://github.com/BigBoot/AutoKuma/pkgs/container/autokuma
    container_name: autokuma
    hostname: autokuma
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "128M"
          pids: 128
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
      # Monitor config
      AUTOKUMA__DEFAULT_SETTINGS: |-
        http.accepted_statuscodes:  [ "200" ]
        http.expiry_notification: true
        http.interval: 60
        http.max_redirects: 1
        http.max_retries: 5
        http.retry_interval: 60
        http.timeout: 30
      AUTOKUMA__KUMA__URL: "${UPTIME_KUMA_URL:?[autokuma] uptime-kuma URL missing}"
      AUTOKUMA__KUMA__USERNAME: "${UPTIME_KUMA_USERNAME:?[autokuma] uptime-kuma username missing}"
      AUTOKUMA__KUMA__PASSWORD: "${UPTIME_KUMA_PASSWORD:?[autokuma] uptime-kuma password missing}"
      AUTOKUMA__ON_DELETE: "keep" # Keep monitors even if the service goes down
      AUTOKUMA__SYNC_INTERVAL: "3600" # Sync every 1 hour
    group_add:
      - "994"  # `getent group docker`
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "pidof", "autokuma" ]
      timeout: 5s
    labels:
      # Metadata configuration to be used by monitors
      # Notifications
      kuma.emby_status.notification.name: 'Emby Status Alert'
      kuma.emby_status.notification.active: 'true'
      kuma.emby_status.notification.config: |
        {
          "type": "discord",
          "disableUrl": false,
          "discordWebhookUrl": "${UPTIME_KUMA_NOTIFICATION_CHANNEL:?[autokuma] Notification channel missing}",
          "discordUsername": "emby-status",
          "discordChannelType": "channel"
        }
      # Tags
      kuma.alertable.tag.name: 'Alertable'
      kuma.alertable.tag.color: '#FFA500'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - autokuma
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"
    volumes:
      # Docker socket mount from host system
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
      # Persistent volumes
      - ../storage/autokuma/data/:/data/
