networks:
  autokuma-ser:
    name: autokuma-ser
    driver: bridge

services:

  # Automatic Uptime-Kuma monitor generator
  autokuma-ser:
    image: ghcr.io/bigboot/autokuma:2.0.0  # https://github.com/BigBoot/AutoKuma/pkgs/container/autokuma
    container_name: autokuma-ser
    hostname: autokuma-ser
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "128M"
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
      # Monitor config
      AUTOKUMA__DEFAULT_SETTINGS: |-
        http.accepted_statuscodes:  [ "200" ]
        http.tag_names: [{"name": "ser" }]
        http.expiry_notification: true
        http.interval: 60
        http.max_redirects: 1
        http.max_retries: 5
        http.retry_interval: 60
        http.timeout: 30
      AUTOKUMA__KUMA__URL: "${UPTIME_KUMA_URL:?[autokuma] UptimeKuma URL missing}"
      AUTOKUMA__ON_DELETE: "keep" # Keep monitors even if the service goes down
      AUTOKUMA__SYNC_INTERVAL: "3600" # Sync every 1 hour
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "pidof", "autokuma" ]
      timeout: 5s
    labels:
      # Metadata configuration to be used by monitors
      # Tags
      kuma.ser.tag.name: 'SER'
      kuma.ser.tag.color: '#FF77FF'
    networks:
      - autokuma-ser
    restart: unless-stopped
    user: "${PUID_ROOT:?User ID missing}:${PGID_ROOT:?Group ID missing}"
    volumes:
      # Docker socket mount from host system
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
      # Persistent volumes
      - ../storage/autokuma-ser/data:/data
