networks:
  bazarr:
    name: bazarr
    driver: bridge

services:

  # Subtitle downloader
  bazarr:
    image: linuxserver/bazarr:1.5.7-development  # https://hub.docker.com/r/linuxserver/bazarr/tags?name=development
    container_name: bazarr
    hostname: bazarr
    cap_drop:
      - ALL
    depends_on:
      radarr:
        condition: service_healthy
      sonarr:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
          pids: 512
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
      PUID: "${PUID_NON_ROOT:?User ID missing}"
      PGID: "${PGID_NON_ROOT:?Group ID missing}"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:6767/api/system/ping" ]
      timeout: 5s
    labels:
      # Reverse proxy config
      traefik.enable: "true"
      traefik.http.routers.bazarr.rule: "Host(`bazarr.${DOMAIN_NAME}`)"
      traefik.http.routers.bazarr.entrypoints: "websecure"
      traefik.http.routers.bazarr.tls: "true"
      traefik.http.routers.bazarr.middlewares: "authelia-forward-auth@file"
      traefik.http.services.bazarr.loadbalancer.server.port: "4009"
      # Monitor config
      kuma.bazarr.http.name: "Bazarr (Subtitle Manager)"
      kuma.bazarr.http.url: "${BAZARR_MONITOR_URL:?[bazarr] Monitor URL missing}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bazarr
      - servarr
    ports:
      - "4009:6767"
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"
    volumes:
      # Volume mounts from host system
      - "${MOVIE_DIRECTORY}:/movies"
      - "${TV1_DIRECTORY}:/tv1"
      - "${TV2_DIRECTORY}:/tv2"
      - "${TV_TRASH_DIRECTORY}:/trash"
      - "${TV_KIDS_DIRECTORY}:/kids"
      # Persistent volumes
      - ../storage/bazarr/config/:/config/
      - ../storage/bazarr/run/:/run/

  # Automated Speech Recognition tool for subtitles
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:v1.9.1  # https://github.com/ahmetoner/whisper-asr-webservice/releases
    container_name: whisper
    hostname: whisper
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8192M"
          pids: 256
    environment:
      # Model config
      ASR_MODEL: "small.en"
      ASR_ENGINE: "faster_whisper"
    healthcheck:
      interval: 60s
      retries: 3
      start_period: 30s
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:9000/docs" ]
      timeout: 15s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bazarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"
    volumes:
      # Persistent volumes
      - ../storage/whisper/cache/:/.cache/
      - ../storage/whisper/config/:/.config/
