networks:
  dash-ser:
    name: dash-ser
    driver: bridge

services:

  # Server performance monitor
  dash-ser:
    image: mauricenino/dashdot:6.3.4  # https://github.com/MauriceNino/dashdot/releases
    container_name: dash-ser
    hostname: dash-ser
    cap_add:
      - DAC_READ_SEARCH
      - SYS_PTRACE
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    environment:
      # General
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: "true"
      DASHDOT_PAGE_TITLE: "${DOMAIN_NAME:-dash.} [SER]"
      DASHDOT_ROUTING_PATH: "/ser"
      DASHDOT_SHOW_DASH_VERSION: "bottom_right"
      DASHDOT_WIDGET_LIST: 'os,cpu,ram,storage,network'
      # CPU
      DASHDOT_ENABLE_CPU_TEMPS: "true"
      DASHDOT_CPU_WIDGET_MIN_WIDTH: "650"
      # OS
      DASHDOT_SHOW_HOST: "true"
      DASHDOT_OS_WIDGET_MIN_WIDTH: "650"
      # Network
      DASHDOT_ACCEPT_OOKLA_EULA: "true"
      # Storage
      DASHDOT_STORAGE_WIDGET_ITEMS_PER_PAGE: "6"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3001/ser/info" ]
      timeout: 5s
    labels:
      # Reverse proxy config
      traefik.enable: "true"
      traefik.docker.network: "dash-ser"
      traefik.http.routers.dash-ser.rule: "Host(`dash.${DOMAIN_NAME}`) && PathPrefix(`/ser`)"
      traefik.http.routers.dash-ser.entrypoints: "websecure"
      traefik.http.routers.dash-ser.tls: "true"
      traefik.http.routers.dash-ser.middlewares: "authelia-forward-auth@file"
      # Monitor config
      kuma.dash-ser.http.name: "Dash [SER] (Server Monitor)"
      kuma.dash-ser.http.url: "${DASH_SER_MONITOR_URL:?[dash-ser] Monitor URL missing}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dash-ser
    ports:
      - '5008:3001'
    privileged: true  # Needed to read RAM details
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_ROOT:?User ID missing}:${PGID_ROOT:?Group ID missing}"
    volumes:
      # Volume mounts from host system
      - "/:/mnt/host:ro"
