# Defining environment variables once to be used in main and sidekiq containers
x-dawarich-env: &dawarich-env
  # Base config
  TIME_ZONE: "${TIMEZONE:?Timezone missing}"
  # Application configuration
  APPLICATION_HOSTS: "localhost,::1,127.0.0.1,map.${DOMAIN_NAME}"
  APPLICATION_PROTOCOL: "http"
  BACKGROUND_PROCESSING_CONCURRENCY: "10"
  MIN_MINUTES_SPENT_IN_CITY: "60"
  PHOTON_API_HOST: "photon:2322"
  PROMETHEUS_EXPORTER_ENABLED: "false"
  RAILS_ENV: "development"  # Other values not currently supported
  REDIS_URL: "redis://dawarich-cache:6379"
  SECRET_KEY_BASE: "${DAWARICH_SECRET_KEY:-[dawarich] Secret key missing}"
  SELF_HOSTED: "true"
  STORE_GEODATA: "true"
  # Authentication configuration
  OIDC_CLIENT_ID: "${DAWARICH_OIDC_CLIENT_ID:?[dawarich] OIDC client ID missing}"
  OIDC_CLIENT_SECRET: "${DAWARICH_OIDC_CLIENT_SECRET:?[dawarich] OIDC client secret missing}"
  OIDC_ISSUER: "${DAWARICH_OIDC_ISSUER_URI:?[dawarich] OIDC issuer URI missing}"
  OIDC_REDIRECT_URI: "${DAWARICH_REDIRECT_URI:?[dawarich] OIDC redirect URI missing}"
  OIDC_AUTO_REGISTER: "false"
  OIDC_PROVIDER_NAME: "Authelia"
  ALLOW_EMAIL_PASSWORD_REGISTRATION: "true"
  # Database configuration
  DATABASE_HOST: "dawarich-db"
  DATABASE_PORT: "${DAWARICH_DB_PORT:?[dawarich] Database port missing}"
  DATABASE_USERNAME: "${DAWARICH_DB_USER:?[dawarich] Database user missing}"
  DATABASE_PASSWORD: "${DAWARICH_DB_PASSWORD:?[dawarich] Database password missing}"
  DATABASE_NAME: "${DAWARICH_DB_NAME:?[dawarich] Database name missing}"
  # Logging configuration
  RAILS_LOG_TO_STDOUT: "true"

networks:
  dawarich:
    name: dawarich
    driver: bridge

services:

  # Google Maps/Timeline Replacement
  dawarich:
    image: freikin/dawarich:0.37.3  # https://github.com/Freika/dawarich/releases
    container_name: dawarich
    hostname: dawarich
    command: [ 'bin/rails', 'server', '-p', '3000', '-b', '::' ]
    entrypoint: web-entrypoint.sh
    depends_on:
      dawarich-cache:
        condition: service_healthy
      dawarich-db:
        condition: service_healthy
      photon:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "4G"
    environment:
      <<: *dawarich-env
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      timeout: 5s
    labels:
      # Reverse proxy config
      traefik.enable: "true"
      traefik.http.routers.dawarich.rule: "Host(`map.${DOMAIN_NAME}`)"
      traefik.http.routers.dawarich.entrypoints: "websecure"
      traefik.http.routers.dawarich.tls: "true"
      traefik.http.routers.dawarich.middlewares: "no-forward-auth@file"
      traefik.http.services.dawarich.loadbalancer.server.port: "4010"
      # Monitor config
      kuma.{{container_name}}.http.name: "Dawarich (Maps Timeline)"
      kuma.{{container_name}}.http.url: "${DAWARICH_MONITOR_URL:?[dawarich] Monitor URL missing}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      - dawarich
    ports:
      - "4010:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      # Persistent volumes
      - ../storage/dawarich/public/:/var/app/public
      - ../storage/dawarich/storage/:/var/app/storage
      - ../storage/dawarich/watched/:/var/app/tmp/imports/watched
      - ../storage/dawarich-db/data/:/dawarich_db_data

  dawarich-sidekiq:
    image: freikin/dawarich:0.37.3  # https://github.com/Freika/dawarich/releases
    container_name: dawarich-sidekiq
    hostname: dawarich-sidekiq
    command: [ 'sidekiq' ]
    entrypoint: sidekiq-entrypoint.sh
    depends_on:
      dawarich:
        condition: service_healthy
      dawarich-cache:
        condition: service_healthy
      dawarich-db:
        condition: service_healthy
      photon:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "4G"
    environment:
      <<: *dawarich-env
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 30s
      test: [ "CMD-SHELL", "pgrep -f sidekiq" ]
      timeout: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      - dawarich
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      # Persistent volumes
      - ../storage/dawarich/public/:/var/app/public
      - ../storage/dawarich/storage/:/var/app/storage
      - ../storage/dawarich/watched/:/var/app/tmp/imports/watched

  dawarich-cache:
    image: valkey/valkey:9.0.1-alpine  # https://hub.docker.com/r/valkey/valkey
    container_name: dawarich-cache
    hostname: dawarich-cache
    command: redis-server
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    environment:
      VALKEY_EXTRA_FLAGS: "--save 60 1 --loglevel warning"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "valkey-cli", "ping" ]
      timeout: 5s
    networks:
      - dawarich
    restart: unless-stopped
    user: "${PUID_ROOT:?User ID missing}:${PGID_ROOT:?Group ID missing}"
    volumes:
      # Persistent volumes
      - ../storage/dawarich/shared/:/data

  dawarich-db:
    image: postgis/postgis:18-3.6-alpine  # https://hub.docker.com/r/postgis/postgis
    container_name: dawarich-db
    hostname: dawarich-db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
      PGTZ: "${TIMEZONE:?Timezone missing}"
      POSTGRES_INITDB_ARGS: "--set=log_timezone=${TIMEZONE:?Timezone missing}"
      # Database config
      POSTGRES_USER: "${DAWARICH_DB_USER:?[dawarich-db] Database user missing}"
      POSTGRES_PASSWORD: "${DAWARICH_DB_PASSWORD:?[dawarich-db] Database password missing}"
      POSTGRES_DB: "${DAWARICH_DB_NAME:?[dawarich-db] Database name missing}"
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "pg_isready", "--host", "localhost", "-U", "${DAWARICH_DB_USER:?[dawarich-db] Database user missing}", "-d", "${DAWARICH_DB_NAME:?[dawarich-db] Database name missing}", "-p", "${DAWARICH_DB_PORT:?[dawarich-db] Database port missing}" ]
      timeout: 5s
    networks:
      - dawarich
    restart: unless-stopped
    shm_size: 1G
    user: "${PUID_ROOT:?User ID missing}:${PGID_ROOT:?Group ID missing}"
    volumes:
      # Persistent volumes
      - ../storage/dawarich-db/:/var/lib/postgresql/
      - ../storage/dawarich/shared/:/var/shared

  # Reverse geo lookups
  photon:
    image: rtuszik/photon-docker:1.3.0  # https://github.com/rtuszik/photon-docker/releases
    container_name: photon
    hostname: photon
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    environment:
      REGION: "${MAP_REGION:-planet}"
      UPDATE_INTERVAL: "720h" # Check for updates every 30 days
      UPDATE_STRATEGY: "PARALLEL"
    expose:
      - "2322"
    networks:
      - dawarich
    restart: unless-stopped
    volumes:
      - ../storage/photon/data/:/photon/data
