networks:
  dozzle:
    name: dozzle
    driver: bridge

services:

  # Docker log viewer
  dozzle:
    image: amir20/dozzle:v8.14.12  # https://github.com/amir20/dozzle/releases
    container_name: dozzle
    hostname: dozzle
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
      # Authentication config
      DOZZLE_AUTH_PROVIDER: "forward-proxy"
      DOZZLE_AUTH_LOGOUT_URL: "${DOZZLE_LOGOUT_URL}"
      # Hosts config
      DOZZLE_HOSTNAME: "${REVERSE_PROXY_HOST_NAME:?[dozzle] Hostname missing}"
      DOZZLE_REMOTE_HOST: "${DOZZLE_REMOTE_HOSTS}"
      # UI config
      DOZZLE_ENABLE_ACTIONS: "true"
      DOZZLE_NO_ANALYTICS: "true"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "/dozzle", "healthcheck" ]
      timeout: 5s
    labels:
      # Reverse proxy config
      traefik.enable: "true"
      traefik.docker.network: "dozzle"
      traefik.http.routers.dozzle.rule: "Host(`log.${DOMAIN_NAME}`)"
      traefik.http.routers.dozzle.entrypoints: "websecure"
      traefik.http.routers.dozzle.tls: "true"
      traefik.http.routers.dozzle.middlewares: "authelia-forward-auth@file"
      # Redirect from 'logs' subdomain to 'log' subdomain
      traefik.http.routers.dozzle-redirect.rule: "Host(`logs.${DOMAIN_NAME}`)"
      traefik.http.routers.dozzle-redirect.entryPoints: "websecure"
      traefik.http.routers.dozzle-redirect.tls: "true"
      traefik.http.routers.dozzle-redirect.middlewares: "dozzle-redirect-regex"
      traefik.http.middlewares.dozzle-redirect-regex.redirectregex.regex: "^https://logs.${DOMAIN_NAME}(.*)"
      traefik.http.middlewares.dozzle-redirect-regex.redirectregex.replacement: "https://log.${DOMAIN_NAME}$${1}"
      traefik.http.middlewares.dozzle-redirect-regex.redirectregex.permanent: "true"
      # Monitor config
      kuma.{{container_name}}.http.name: "Dozzle (Docker Log Viewer)"
      kuma.{{container_name}}.http.url: "${DOZZLE_MONITOR_URL:?[dozzle] Monitor URL missing}"
    networks:
      - dozzle
    ports:
      - "5005:8080"
    restart: unless-stopped
    user: "${PUID_ROOT:?User ID missing}:${PGID_ROOT:?Group ID missing}"
    volumes:
      # Docker socket mount from host system
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
