networks:
  navidrome:
    name: navidrome
    driver: bridge

services:

  # Music Player
  navidrome:
    image: deluan/navidrome:0.63.2  # https://github.com/navidrome/navidrome/releases/
    container_name: navidrome
    hostname: navidrome
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
          pids: 128
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
      # Authentication config
      ND_EXTAUTH_TRUSTEDSOURCES: "0.0.0.0/0"
      ND_EXTAUTH_USERHEADER: "Remote-User"
      ND_EXTAUTH_LOGOUTURL: "${NAVIDROME_OIDC_LOGOUT_URL?:[navidrome] OIDC logout URL missing}"
      ND_SESSIONTIMEOUT: "672h"  # 4 weeks
      # External services config
      ND_LASTFM_APIKEY: "${LASTFM_API_KEY:?[navidrome] LastFM API key missing}"
      ND_LASTFM_SECRET: "${LASTFM_SECRET:?[navidrome] LastFM secret missing}"
      # Scheduling config
      ND_SCANNER_SCHEDULE: "@every 24h"
      # Metadata config
      ND_ARTISTARTPRIORITY: "artist.*,external"
      ND_COVERARTPRIORITY: "album.*,embedded,external"
      ND_LYRICSPRIORITY: ".lrc,.txt,.elrc,embedded"
      # Logging config
      ND_LOGLEVEL: "info"
      # Plugins
      ND_PLUGINS_ENABLED: "false"
      ND_PLUGINS_AUTORELOAD: "false"
      # System config
      ND_ENABLEINSIGHTSCOLLECTOR: "false"
      ND_ENABLESHARING: "false"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:4533/ping" ]
      timeout: 5s
    labels:
      # Reverse proxy config
      traefik.enable: "true"
      traefik.http.routers.navidrome.rule: "Host(`music.${DOMAIN_NAME}`)"
      traefik.http.routers.navidrome.entrypoints: "websecure"
      traefik.http.routers.navidrome.tls: "true"
      traefik.http.routers.navidrome.middlewares: "authelia-forward-auth@file"
      traefik.http.services.navidrome.loadbalancer.server.port: "4003"
      # Monitor config
      kuma.navidrome.http.name: "Navidrome (Music Player)"
      kuma.navidrome.http.url: "${NAVIDROME_MONITOR_URL:?[navidrome] Monitor URL missing}"
      kuma.navidrome.http.max_redirects: "0"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - navidrome
    ports:
      - "4003:4533"
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"
    volumes:
      # Volume mounts from host system
      - "${MUSIC_DIRECTORY}:/music:ro"
      - "${PODCAST_DIRECTORY}:/podcast:ro"
      # Persistent volumes
      - ../storage/navidrome/data/:/data/
