networks:
  prowlarr:
    name: prowlarr
    driver: bridge

services:

  # Indexer (Torrents + Usenet)
  prowlarr:
    image: linuxserver/prowlarr:2.3.6-nightly  # https://hub.docker.com/r/linuxserver/prowlarr/tags?name=nightly
    container_name: prowlarr
    hostname: prowlarr
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    depends_on:
      flaresolverr:
        condition: service_healthy
      lidarr:
        condition: service_healthy
      radarr:
        condition: service_healthy
      readarr:
        condition: service_healthy
      sonarr:
        condition: service_healthy
      sportarr:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
          pids: 512 # High memory resourcing to allow stats page to load
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:9696/ping" ]
      timeout: 5s
    labels:
      # Reverse proxy config
      traefik.enable: "true"
      traefik.http.routers.prowlarr.rule: "Host(`prowlarr.${DOMAIN_NAME}`)"
      traefik.http.routers.prowlarr.entrypoints: "websecure"
      traefik.http.routers.prowlarr.tls: "true"
      traefik.http.routers.prowlarr.middlewares: "authelia-forward-auth@file"
      traefik.http.services.prowlarr.loadbalancer.server.port: "4016"
      # Monitor config
      kuma.prowlarr.http.name: "Prowlarr (Torrent Indexer)"
      kuma.prowlarr.http.url: "${PROWLARR_MONITOR_URL:?[prowlarr] Monitor URL missing}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prowlarr
      - servarr
      - sportarr
    ports:
      - "4016:9696"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"
    volumes:
      # Persistent volumes
      - ../storage/prowlarr/config/:/config/
      - ../storage/prowlarr/run/:/run/

  # Cloudflare rate-limiter solver
  flaresolverr:
    image: flaresolverr/flaresolverr:v3.4.6  # https://hub.docker.com/r/flaresolverr/flaresolverr/tags
    container_name: flaresolverr
    hostname: flaresolverr
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "512M"
          pids: 512
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
      # Logging config
      LOG_LEVEL: "info"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "curl", "--silent", "--fail", "http://127.0.0.1:8191/" ] # wget not installed
      timeout: 5s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prowlarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"
    volumes:
      # Persistent volumes
      - ../storage/flaresolverr/config/:/config/
