networks:
  romm:
    name: romm
    driver: bridge

services:

  # Video Game ROM Manager
  romm:
    image: rommapp/romm:4.8.1  # https://github.com/rommapp/romm/releases
    container_name: romm
    hostname: romm
    cap_drop:
      - ALL
    depends_on:
      romm-cache:
        condition: service_healthy
      romm-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2048M"
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
      # Authentication config
      DISABLE_SETUP_WIZARD: "true"  # Set to 'true' for initial set-up
      DISABLE_USERPASS_LOGIN: "true"  # Set to 'true' for initial set-up
      OIDC_AUTOLOGIN: "true"
      OIDC_CLAIM_ROLES: "groups"
      OIDC_CLIENT_ID: "${ROMM_OIDC_CLIENT_ID:?[romm] OIDC client ID missing}"
      OIDC_CLIENT_SECRET: "${ROMM_OIDC_CLIENT_SECRET:?[romm] OIDC client secret missing}"
      OIDC_ENABLED: "true"
      OIDC_END_SESSION_ENDPOINT: "${ROMM_OIDC_LOGOUT_URL:?[romm] RomM logout URL missing}"
      OIDC_PROVIDER: "Authelia"
      OIDC_REDIRECT_URI: "${ROMM_OIDC_REDIRECT_URL:?[romm] RomM redirect URL missing}"
      OIDC_ROLE_ADMIN: "romm_admins"
      OIDC_ROLE_VIEWER: "romm_users"
      OIDC_SERVER_APPLICATION_URL: "${ROMM_OIDC_URL:?[romm] OIDC URL missing}"
      # Task config
      ENABLE_RESCAN_ON_FILESYSTEM_CHANGE: "true"
      ENABLE_SCHEDULED_CONVERT_IMAGES_TO_WEBP: "true"
      ENABLE_SCHEDULED_RESCAN: "true"
      ENABLE_SCHEDULED_RETROACHIEVEMENTS_PROGRESS_SYNC: "true"
      ENABLE_SCHEDULED_UPDATE_LAUNCHBOX_METADATA: "false"
      # Cache config
      REDIS_HOST: "romm-cache"
      REDIS_PORT: "6379"
      # Database config
      ROMM_DB_DRIVER: "postgresql"
      DB_HOST: "romm-db"
      DB_NAME: "${ROMM_DB_NAME:?[romm] Database name missing}"
      DB_PORT: "${ROMM_DB_PORT:?[romm] Database port missing}"
      DB_PASSWD: "${ROMM_DB_PASSWORD:?[romm] Database password missing}"
      DB_USER: "${ROMM_DB_USER:?[romm] Database user missing}"
      # External systems config
      FLASHPOINT_API_ENABLED: "true"
      HASHEOUS_API_ENABLED: "true"    # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#hasheous
      HLTB_API_ENABLED: "true"
      LAUNCHBOX_API_ENABLED: "false"  # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#launchbox
      PLAYMATCH_API_ENABLED: "true"   # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#playmatch
      # External systems credentials
      IGDB_CLIENT_ID: "${TWITCH_CLIENT_ID:?[romm] Twitch client ID missing}"
      IGDB_CLIENT_SECRET: "${TWITCH_CLIENT_SECRET:?[romm] Twitch client secret missing}"
      MOBYGAMES_API_KEY: "${MOBYGAMES_API_KEY:-}"
      RETROACHIEVEMENTS_API_KEY: "${RETROACHIEVEMENTS_API_KEY:-}"
      SCREENSCRAPER_USER: "${SCREENSCRAPER_USER:-}"
      SCREENSCRAPER_PASSWORD: "${SCREENSCRAPER_PASSWORD:-}"
      STEAMGRIDDB_API_KEY: "${STEAMGRIDDB_API_KEY:-}"  # Not picked up in scanners, only for manual image searches
      # Logging config
      FORCE_COLOR: "true"
      LOGLEVEL: "INFO"
      # Network config
      IPV4_ONLY: "true"
      # Secrets config
      ROMM_AUTH_SECRET_KEY: "${ROMM_SECRET_KEY:?[romm] Authentication secret key missing}"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/api/heartbeat" ]
      timeout: 5s
    labels:
      # Reverse proxy config
      traefik.enable: "true"
      traefik.http.routers.romm.rule: "Host(`game.${DOMAIN_NAME}`)"
      traefik.http.routers.romm.entrypoints: "websecure"
      traefik.http.routers.romm.tls: "true"
      traefik.http.routers.romm.middlewares: "no-forward-auth@file"
      traefik.http.services.romm.loadbalancer.server.port: "4006"
      # Redirect from 'games' subdomain to 'game' subdomain
      traefik.http.routers.romm-redirect.rule: "Host(`games.${DOMAIN_NAME}`)"
      traefik.http.routers.romm-redirect.entryPoints: "websecure"
      traefik.http.routers.romm-redirect.tls: "true"
      traefik.http.routers.romm-redirect.middlewares: "romm-redirect-regex"
      traefik.http.middlewares.romm-redirect-regex.redirectregex.regex: "^https://games.${DOMAIN_NAME}(.*)"
      traefik.http.middlewares.romm-redirect-regex.redirectregex.replacement: "https://game.${DOMAIN_NAME}$${1}"
      traefik.http.middlewares.romm-redirect-regex.redirectregex.permanent: "true"
      # Monitor config
      kuma.romm.http.name: "RomM (Game ROM Manager)"
      kuma.romm.http.url: "${ROMM_MONITOR_URL:?[romm] Monitor URL missing}"
    networks:
      - romm
    ports:
      - "4006:8080"
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"
    volumes:
      # Volume mounts from host system
      - "${ROM_GAMES_AND_BIOS_PARENT_DIRECTORY}:/romm/library:ro"
      - "${ROM_SAVES_DIRECTORY}:/romm/assets"
      - "../docker/romm/config/:/romm/config"
      # Persistent volumes
      - ../storage/romm/resources/:/romm/resources/  # Resources (covers, screenshots, etc.) that are fetched externally
      - ../storage/romm/redis/:/redis-data/          # Cached data for background tasks

  # External cache for RomM (used due to an issue with the internal valkey)
  romm-cache:
    image: valkey/valkey:9.0.3-alpine  # https://hub.docker.com/r/valkey/valkey
    container_name: romm-cache
    hostname: romm-cache
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
    environment:
      VALKEY_EXTRA_FLAGS: "--save 60 1 --loglevel warning"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "valkey-cli", "ping" ]
      timeout: 5s
    networks:
      - romm
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "999:1000"  # valkey user
    volumes:
      # Persistent volumes
      - ../storage/romm-cache/data/:/data

  # Database for RomM
  romm-db:
    image: postgres:18.3-alpine  # https://hub.docker.com/_/postgres
    container_name: romm-db
    hostname: romm-db
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
      PGTZ: "${TIMEZONE:?Timezone missing}"
      POSTGRES_INITDB_ARGS: "--set=log_timezone=${TIMEZONE:?Timezone missing}"
      # Database config
      PGPORT: "${ROMM_DB_PORT:?[romm-db] Database port missing}"
      POSTGRES_DB: "${ROMM_DB_NAME:?[romm-db] Database name missing}"
      POSTGRES_PASSWORD: "${ROMM_DB_PASSWORD:?[romm-db] Database password missing}"
      POSTGRES_USER: "${ROMM_DB_USER:?[romm-db] Database user missing}"
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - "${ROMM_DB_PORT:?[romm-db] Database port missing}"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "pg_isready", "--host", "localhost", "-U", "${ROMM_DB_USER:?[romm-db] Database user missing}", "-d", "${ROMM_DB_NAME:?[romm-db] Database name missing}", "-p", "${ROMM_DB_PORT:?[romm-db] Database port missing}" ]
      timeout: 5s
    networks:
      - romm
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
      - /var/run/postgresql:uid=999,gid=999,mode=775  # Giving access to startup root execution
    user: "999:999"  # postgres user
    volumes:
      # Persistent volumes
      - ../storage/romm-db/:/var/lib/postgresql/
