networks:
  speedtest:
    name: speedtest
    driver: bridge

services:

  # Automated SpeedTest runner with graphs
  speedtest:
    image: linuxserver/speedtest-tracker:1.13.11  # https://github.com/alexjustesen/speedtest-tracker/releases
    container_name: speedtest
    hostname: speedtest
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    depends_on:
      speedtest-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"
    environment:
      # Base config
      APP_TIMEZONE: "${TIMEZONE:?Timezone missing}"
      PGID: "${PGID_NON_ROOT:?Group ID missing}"
      PUID: "${PUID_NON_ROOT:?User ID missing}"
      # Reporting config
      APP_KEY: "${SPEEDTEST_APP_KEY:?[speedtest] App key missing}"
      APP_URL: "${SPEEDTEST_APP_URL:?[speedtest] App URL missing}"
      PRUNE_RESULTS_OLDER_THAN: "30" # Days
      SPEEDTEST_SCHEDULE: "${SPEEDTEST_SCHEDULE?:[speedtest] Cron schedule missing}"
      SPEEDTEST_SERVERS: "${SPEEDTEST_SERVERS}"
      # Database config
      DB_CONNECTION: "pgsql"
      DB_HOST: "speedtest-db"
      DB_DATABASE: "${SPEEDTEST_DB_NAME:?[speedtest] Database name missing}"
      DB_PASSWORD: "${SPEEDTEST_DB_PASSWORD:?[speedtest] Database password missing}"
      DB_PORT: "${SPEEDTEST_DB_PORT:?[speedtest] Database port missing}"
      DB_USERNAME: "${SPEEDTEST_DB_USER:?[speedtest] Database user missing}"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "-O", "-", "http://127.0.0.1:80/api/speedtest/latest" ]
      timeout: 5s
    labels:
      # Reverse proxy config
      traefik.enable: "true"
      traefik.docker.network: "speedtest"
      traefik.http.routers.speedtest.rule: "Host(`speedtest.${DOMAIN_NAME}`)"
      traefik.http.routers.speedtest.entrypoints: "websecure"
      traefik.http.routers.speedtest.tls: "true"
      traefik.http.routers.speedtest.middlewares: "no-forward-auth@file"
      # Monitor config
      kuma.speedtest.http.name: "SpeedTest Tracker (Network Speed Test)"
      kuma.speedtest.http.url: "${SPEEDTEST_MONITOR_URL:?[speedtest] Monitor URL missing}"
    networks:
      - speedtest
    ports:
      - "5004:80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    # user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"  # Doesn't work, must use environment variables
    volumes:
      # Persistent volumes
      - ../storage/speedtest/config/:/config/

  # Database for SpeedTest
  speedtest-db:
    image: postgres:18.3-alpine  # https://hub.docker.com/_/postgres
    container_name: speedtest-db
    hostname: speedtest-db
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    environment:
      # Base config
      TZ: "${TIMEZONE:?Timezone missing}"
      PGTZ: "${TIMEZONE:?Timezone missing}"
      POSTGRES_INITDB_ARGS: "--set=log_timezone=${TIMEZONE:?Timezone missing}"
      # Database config
      PGPORT: "${SPEEDTEST_DB_PORT:?[speedtest-db] Database port missing}"
      POSTGRES_DB: "${SPEEDTEST_DB_NAME:?[speedtest-db] Database name missing}"
      POSTGRES_PASSWORD: "${SPEEDTEST_DB_PASSWORD:?[speedtest-db] Database password missing}"
      POSTGRES_USER: "${SPEEDTEST_DB_USER:?[speedtest-db] Database user missing}"
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - "${SPEEDTEST_DB_PORT:?[speedtest-db] Missing DB port}"
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "pg_isready", "--host", "localhost", "-U", "${SPEEDTEST_DB_USER:?[speedtest-db] Database user missing}", "-d", "${SPEEDTEST_DB_NAME:?[speedtest-db] Database name missing}", "-p", "${SPEEDTEST_DB_PORT:?[speedtest-db] Database port missing}" ]
      timeout: 5s
    networks:
      - speedtest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
      - /var/run/postgresql:uid=999,gid=999,mode=775  # Giving access to startup root execution
    user: "999:999"  # postgres user
    volumes:
      # Persistent volumes
      - ../storage/speedtest-db/:/var/lib/postgresql/
