networks:
  traefik-kop:
    name: traefik-kop
    driver: bridge

services:

  # Traefik connector
  traefik-kop:
    image: ghcr.io/jittering/traefik-kop:0.20.1  # https://github.com/jittering/traefik-kop/releases
    container_name: traefik-kop
    hostname: traefik-kop
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "512M"
          pids: 128
    environment:
      BIND_IP: "${MAIN_HOST_IP}" # IP address of this host
      REDIS_ADDR: "${REVERSE_PROXY_HOST_IP}:6379" # Port of the redis instance on the reverse proxy host
    group_add:
      - "994"  # `getent group docker`
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "/traefik-kop", "-V" ]
      timeout: 5s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - traefik-kop
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"
    volumes:
      # Docker socket mount from host system
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
