networks:
  traefik-oracle:
    name: traefik-oracle
    driver: bridge

services:

  # Reverse proxy
  traefik-oracle:
    image: traefik:v3.6.15  # https://github.com/traefik/traefik/releases
    container_name: traefik-oracle
    hostname: traefik-oracle
    command: --configFile=/config/traefik-oracle.yml
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
          pids: 256
    group_add:
      - "988"  # `getent group docker`
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      timeout: 5s
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - traefik-oracle
      - uptime-kuma
    ports:
      - "443:443"
      - "5555:8080"
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT_ORACLE:?User ID missing}:${PGID_NON_ROOT_ORACLE:?Group ID missing}"
    volumes:
      # Docker socket mount from host system
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
      # Volume mounts from host system
      - ../docker/traefik/config/traefik-oracle.yml:/config/traefik-oracle.yml:ro
      - ../docker/traefik/certs/cloudflare_origin_cert.pem:/etc/certs/cloudflare_origin_cert.pem:ro
      - ../docker/traefik/certs/cloudflare_origin_key.pem:/etc/certs/cloudflare_origin_key.pem:ro
      # Persistent volumes
      - ../storage/traefik-oracle/logs/access/:/var/log/traefik/access/
