networks:
  watchstate:
    name: watchstate
    driver: bridge

services:

  # Tool to import/export played state of media in Emby, instead of using Trakt
  watchstate:
    image: ghcr.io/arabcoders/watchstate:v1.0.8  # https://github.com/arabcoders/watchstate/releases
    container_name: watchstate
    hostname: watchstate
    cap_drop:
      - ALL
    environment:
      # Base config
      TIMEZONE: "${TIMEZONE:?Timezone missing}"
      # Logging config
      WS_LOGGER_FILE_ENABLE: "false" # Disabled due to logs being too large, and not needing them
    healthcheck: # Default healthcheck fails at the start, before eventually passing which breaks scripts
      interval: 30s
      retries: 3
      start_period: 30s
      test: [ "CMD", "curl", "--silent", "--fail", "http://127.0.0.1:8080/v1/api/system/healthcheck" ] # wget not installed
      timeout: 5s
    networks:
      - watchstate
    ports:
      - "5006:8080"
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    tmpfs:
      - /tmp:size=64m,noexec,nosuid,nodev
    user: "${PUID_NON_ROOT:?User ID missing}:${PGID_NON_ROOT:?Group ID missing}"
    volumes:
      # Persistent volumes
      - ../storage/watchstate/data:/config/
