# Traefik 3.x (YAML)
# Taken from https://github.com/brokenscripts/authentik_traefik/blob/traefik3/appdata/traefik/config/traefik.yaml

################################################################
# Global configuration - https://doc.traefik.io/traefik/reference/static-configuration/file/
################################################################

global:
  checkNewVersion: false
  sendAnonymousUsage: false
  
serversTransport:
  forwardingTimeouts:
    dialTimeout: 20s # Default timeout to connect to a backend service
  
################################################################
# Logs - https://doc.traefik.io/traefik/observability/logs/
################################################################

log:
  level: DEBUG # Options: DEBUG, PANIC, FATAL, ERROR (Default), WARN, and INFO
  noColor: false
  maxSize: 100 # In megabytes
  compress: true # gzip compression when rotating

################################################################
# API and Dashboard
################################################################

api:
  dashboard: true
  insecure: true # Update this
ping: {}

################################################################
# Entrypoints - https://doc.traefik.io/traefik/routing/entrypoints/
################################################################

entryPoints:
  web:
    address: ":80"
    http:
      # Global HTTP to HTTPS redirection      
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls: {}
    forwardedHeaders:
      trustedIPs:
        # Cloudflare (https://www.cloudflare.com/ips-v4)
        - "173.245.48.0/20"
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "141.101.64.0/18"
        - "108.162.192.0/18"
        - "190.93.240.0/20"
        - "188.114.96.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "162.158.0.0/15"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
        - "172.64.0.0/13"
        - "131.0.72.0/22"
        # Local IPs
        - "127.0.0.1/32"
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

################################################################
# Providers - https://doc.traefik.io/traefik/providers/docker/
################################################################

providers:
  # Enable auto loading of newly created rules by watching a directory
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  redis:
    endpoints:
      - traefik-provider:6379
  file:
    directory: /file_configs # Apps, LoadBalancers, TLS Options, Middlewares, Middleware Chains
    watch: true


################################################################
# Plugins - https://plugins.traefik.io/plugins
################################################################

experimental:
  plugins:
    # Used to redirect when services are down
    traefik-plugin-redirect-on-status:
      moduleName: "github.com/m-riedel/traefik-plugin-redirect-on-status"
      version: "v1.0.1"

